/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVencimentosRouteImport } from './routes/_authenticated.vencimentos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated.usuarios'
import { Route as AuthenticatedTrabalhadoresRouteImport } from './routes/_authenticated.trabalhadores'
import { Route as AuthenticatedSetoresRouteImport } from './routes/_authenticated.setores'
import { Route as AuthenticatedServicosCatalogoRouteImport } from './routes/_authenticated.servicos-catalogo'
import { Route as AuthenticatedRiscosOcupacionaisRouteImport } from './routes/_authenticated.riscos-ocupacionais'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated.propostas'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated.profissionais'
import { Route as AuthenticatedOrdensServicoRouteImport } from './routes/_authenticated.ordens-servico'
import { Route as AuthenticatedMedidasControleRouteImport } from './routes/_authenticated.medidas-controle'
import { Route as AuthenticatedImportacaoCadastrosRouteImport } from './routes/_authenticated.importacao-cadastros'
import { Route as AuthenticatedImportacaoRouteImport } from './routes/_authenticated.importacao'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated.historico'
import { Route as AuthenticatedGesRouteImport } from './routes/_authenticated.ges'
import { Route as AuthenticatedFuncoesRouteImport } from './routes/_authenticated.funcoes'
import { Route as AuthenticatedEsocialRouteImport } from './routes/_authenticated.esocial'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated.empresas'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated.documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContabilidadesRouteImport } from './routes/_authenticated.contabilidades'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedEmpresasEmpresaIdRouteImport } from './routes/_authenticated.empresas.$empresaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVencimentosRoute =
  AuthenticatedVencimentosRouteImport.update({
    id: '/vencimentos',
    path: '/vencimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrabalhadoresRoute =
  AuthenticatedTrabalhadoresRouteImport.update({
    id: '/trabalhadores',
    path: '/trabalhadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetoresRoute = AuthenticatedSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicosCatalogoRoute =
  AuthenticatedServicosCatalogoRouteImport.update({
    id: '/servicos-catalogo',
    path: '/servicos-catalogo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRiscosOcupacionaisRoute =
  AuthenticatedRiscosOcupacionaisRouteImport.update({
    id: '/riscos-ocupacionais',
    path: '/riscos-ocupacionais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdensServicoRoute =
  AuthenticatedOrdensServicoRouteImport.update({
    id: '/ordens-servico',
    path: '/ordens-servico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMedidasControleRoute =
  AuthenticatedMedidasControleRouteImport.update({
    id: '/medidas-controle',
    path: '/medidas-controle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportacaoCadastrosRoute =
  AuthenticatedImportacaoCadastrosRouteImport.update({
    id: '/importacao-cadastros',
    path: '/importacao-cadastros',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportacaoRoute = AuthenticatedImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGesRoute = AuthenticatedGesRouteImport.update({
  id: '/ges',
  path: '/ges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFuncoesRoute = AuthenticatedFuncoesRouteImport.update({
  id: '/funcoes',
  path: '/funcoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEsocialRoute = AuthenticatedEsocialRouteImport.update({
  id: '/esocial',
  path: '/esocial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContabilidadesRoute =
  AuthenticatedContabilidadesRouteImport.update({
    id: '/contabilidades',
    path: '/contabilidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresasEmpresaIdRoute =
  AuthenticatedEmpresasEmpresaIdRouteImport.update({
    id: '/$empresaId',
    path: '/$empresaId',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contabilidades': typeof AuthenticatedContabilidadesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/esocial': typeof AuthenticatedEsocialRoute
  '/funcoes': typeof AuthenticatedFuncoesRoute
  '/ges': typeof AuthenticatedGesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/importacao-cadastros': typeof AuthenticatedImportacaoCadastrosRoute
  '/medidas-controle': typeof AuthenticatedMedidasControleRoute
  '/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/riscos-ocupacionais': typeof AuthenticatedRiscosOcupacionaisRoute
  '/servicos-catalogo': typeof AuthenticatedServicosCatalogoRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/trabalhadores': typeof AuthenticatedTrabalhadoresRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vencimentos': typeof AuthenticatedVencimentosRoute
  '/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contabilidades': typeof AuthenticatedContabilidadesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/esocial': typeof AuthenticatedEsocialRoute
  '/funcoes': typeof AuthenticatedFuncoesRoute
  '/ges': typeof AuthenticatedGesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/importacao-cadastros': typeof AuthenticatedImportacaoCadastrosRoute
  '/medidas-controle': typeof AuthenticatedMedidasControleRoute
  '/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/riscos-ocupacionais': typeof AuthenticatedRiscosOcupacionaisRoute
  '/servicos-catalogo': typeof AuthenticatedServicosCatalogoRoute
  '/setores': typeof AuthenticatedSetoresRoute
  '/trabalhadores': typeof AuthenticatedTrabalhadoresRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vencimentos': typeof AuthenticatedVencimentosRoute
  '/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contabilidades': typeof AuthenticatedContabilidadesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/_authenticated/esocial': typeof AuthenticatedEsocialRoute
  '/_authenticated/funcoes': typeof AuthenticatedFuncoesRoute
  '/_authenticated/ges': typeof AuthenticatedGesRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/importacao': typeof AuthenticatedImportacaoRoute
  '/_authenticated/importacao-cadastros': typeof AuthenticatedImportacaoCadastrosRoute
  '/_authenticated/medidas-controle': typeof AuthenticatedMedidasControleRoute
  '/_authenticated/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/_authenticated/propostas': typeof AuthenticatedPropostasRoute
  '/_authenticated/riscos-ocupacionais': typeof AuthenticatedRiscosOcupacionaisRoute
  '/_authenticated/servicos-catalogo': typeof AuthenticatedServicosCatalogoRoute
  '/_authenticated/setores': typeof AuthenticatedSetoresRoute
  '/_authenticated/trabalhadores': typeof AuthenticatedTrabalhadoresRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vencimentos': typeof AuthenticatedVencimentosRoute
  '/_authenticated/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/contabilidades'
    | '/dashboard'
    | '/documentos'
    | '/empresas'
    | '/esocial'
    | '/funcoes'
    | '/ges'
    | '/historico'
    | '/importacao'
    | '/importacao-cadastros'
    | '/medidas-controle'
    | '/ordens-servico'
    | '/profissionais'
    | '/propostas'
    | '/riscos-ocupacionais'
    | '/servicos-catalogo'
    | '/setores'
    | '/trabalhadores'
    | '/usuarios'
    | '/vencimentos'
    | '/empresas/$empresaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/contabilidades'
    | '/dashboard'
    | '/documentos'
    | '/empresas'
    | '/esocial'
    | '/funcoes'
    | '/ges'
    | '/historico'
    | '/importacao'
    | '/importacao-cadastros'
    | '/medidas-controle'
    | '/ordens-servico'
    | '/profissionais'
    | '/propostas'
    | '/riscos-ocupacionais'
    | '/servicos-catalogo'
    | '/setores'
    | '/trabalhadores'
    | '/usuarios'
    | '/vencimentos'
    | '/empresas/$empresaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contabilidades'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/empresas'
    | '/_authenticated/esocial'
    | '/_authenticated/funcoes'
    | '/_authenticated/ges'
    | '/_authenticated/historico'
    | '/_authenticated/importacao'
    | '/_authenticated/importacao-cadastros'
    | '/_authenticated/medidas-controle'
    | '/_authenticated/ordens-servico'
    | '/_authenticated/profissionais'
    | '/_authenticated/propostas'
    | '/_authenticated/riscos-ocupacionais'
    | '/_authenticated/servicos-catalogo'
    | '/_authenticated/setores'
    | '/_authenticated/trabalhadores'
    | '/_authenticated/usuarios'
    | '/_authenticated/vencimentos'
    | '/_authenticated/empresas/$empresaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vencimentos': {
      id: '/_authenticated/vencimentos'
      path: '/vencimentos'
      fullPath: '/vencimentos'
      preLoaderRoute: typeof AuthenticatedVencimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trabalhadores': {
      id: '/_authenticated/trabalhadores'
      path: '/trabalhadores'
      fullPath: '/trabalhadores'
      preLoaderRoute: typeof AuthenticatedTrabalhadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setores': {
      id: '/_authenticated/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof AuthenticatedSetoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servicos-catalogo': {
      id: '/_authenticated/servicos-catalogo'
      path: '/servicos-catalogo'
      fullPath: '/servicos-catalogo'
      preLoaderRoute: typeof AuthenticatedServicosCatalogoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/riscos-ocupacionais': {
      id: '/_authenticated/riscos-ocupacionais'
      path: '/riscos-ocupacionais'
      fullPath: '/riscos-ocupacionais'
      preLoaderRoute: typeof AuthenticatedRiscosOcupacionaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordens-servico': {
      id: '/_authenticated/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof AuthenticatedOrdensServicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medidas-controle': {
      id: '/_authenticated/medidas-controle'
      path: '/medidas-controle'
      fullPath: '/medidas-controle'
      preLoaderRoute: typeof AuthenticatedMedidasControleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importacao-cadastros': {
      id: '/_authenticated/importacao-cadastros'
      path: '/importacao-cadastros'
      fullPath: '/importacao-cadastros'
      preLoaderRoute: typeof AuthenticatedImportacaoCadastrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importacao': {
      id: '/_authenticated/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AuthenticatedImportacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ges': {
      id: '/_authenticated/ges'
      path: '/ges'
      fullPath: '/ges'
      preLoaderRoute: typeof AuthenticatedGesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funcoes': {
      id: '/_authenticated/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof AuthenticatedFuncoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/esocial': {
      id: '/_authenticated/esocial'
      path: '/esocial'
      fullPath: '/esocial'
      preLoaderRoute: typeof AuthenticatedEsocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contabilidades': {
      id: '/_authenticated/contabilidades'
      path: '/contabilidades'
      fullPath: '/contabilidades'
      preLoaderRoute: typeof AuthenticatedContabilidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas/$empresaId': {
      id: '/_authenticated/empresas/$empresaId'
      path: '/$empresaId'
      fullPath: '/empresas/$empresaId'
      preLoaderRoute: typeof AuthenticatedEmpresasEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
  }
}

interface AuthenticatedEmpresasRouteChildren {
  AuthenticatedEmpresasEmpresaIdRoute: typeof AuthenticatedEmpresasEmpresaIdRoute
}

const AuthenticatedEmpresasRouteChildren: AuthenticatedEmpresasRouteChildren = {
  AuthenticatedEmpresasEmpresaIdRoute: AuthenticatedEmpresasEmpresaIdRoute,
}

const AuthenticatedEmpresasRouteWithChildren =
  AuthenticatedEmpresasRoute._addFileChildren(
    AuthenticatedEmpresasRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContabilidadesRoute: typeof AuthenticatedContabilidadesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRouteWithChildren
  AuthenticatedEsocialRoute: typeof AuthenticatedEsocialRoute
  AuthenticatedFuncoesRoute: typeof AuthenticatedFuncoesRoute
  AuthenticatedGesRoute: typeof AuthenticatedGesRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedImportacaoRoute: typeof AuthenticatedImportacaoRoute
  AuthenticatedImportacaoCadastrosRoute: typeof AuthenticatedImportacaoCadastrosRoute
  AuthenticatedMedidasControleRoute: typeof AuthenticatedMedidasControleRoute
  AuthenticatedOrdensServicoRoute: typeof AuthenticatedOrdensServicoRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRoute
  AuthenticatedRiscosOcupacionaisRoute: typeof AuthenticatedRiscosOcupacionaisRoute
  AuthenticatedServicosCatalogoRoute: typeof AuthenticatedServicosCatalogoRoute
  AuthenticatedSetoresRoute: typeof AuthenticatedSetoresRoute
  AuthenticatedTrabalhadoresRoute: typeof AuthenticatedTrabalhadoresRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVencimentosRoute: typeof AuthenticatedVencimentosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContabilidadesRoute: AuthenticatedContabilidadesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRouteWithChildren,
  AuthenticatedEsocialRoute: AuthenticatedEsocialRoute,
  AuthenticatedFuncoesRoute: AuthenticatedFuncoesRoute,
  AuthenticatedGesRoute: AuthenticatedGesRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedImportacaoRoute: AuthenticatedImportacaoRoute,
  AuthenticatedImportacaoCadastrosRoute: AuthenticatedImportacaoCadastrosRoute,
  AuthenticatedMedidasControleRoute: AuthenticatedMedidasControleRoute,
  AuthenticatedOrdensServicoRoute: AuthenticatedOrdensServicoRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRoute,
  AuthenticatedRiscosOcupacionaisRoute: AuthenticatedRiscosOcupacionaisRoute,
  AuthenticatedServicosCatalogoRoute: AuthenticatedServicosCatalogoRoute,
  AuthenticatedSetoresRoute: AuthenticatedSetoresRoute,
  AuthenticatedTrabalhadoresRoute: AuthenticatedTrabalhadoresRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVencimentosRoute: AuthenticatedVencimentosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
